// FILE: app/data.ts

import { image } from "framer-motion/client";

export const PROJECTS = [
  { 
    id: "statmize-website",
    title: "Statmize Website", 
    tag: "Next.js Web", 
    shortDesc: "Marketing site with SEO focus.", 
    fullDesc: "A sleek marketing website for the Statmize app, designed to convert visitors into users through clear CTAs and engaging content.",   
    techStack: ["Next.js 14", "Tailwind CSS", "Framer Motion"],
    challenge: "Balancing rich media content with fast load times for SEO.",
    solution: "Used optimized images, code-splitting, and prioritized loading strategies to keep the site performant.",
    link: "https://statmize.vercel.app",
    image: "/projects/statmize-website.png",
  },
   { 
    id: "heerak-food",
    title: "Heerak Food", 
    tag: "Next.js Web", 
    shortDesc: "Realtime feedback, responsive e-commerce presence.", 
    fullDesc: "A high-conversion landing page and product catalog for a food supply business. Focuses on SEO, fast load times (Core Web Vitals), and ease of contact.",
    techStack: ["Next.js 14", "Tailwind CSS", "Framer Motion", "Firebase"],
    challenge: "Making the site feel 'premium' while maintaining a 100/100 Lighthouse performance score.",
    solution: "Leveraged Next.js Image optimization and lazy-loading for animations. Used strict component modularity to keep the bundle size minimal.",
    link: "https://heerakfood.in",
    image: "/projects/heerakfood.png",
  },
  { 
    id: "connectogrowth",
    title: "ConnectoGrowth", 
    tag: "Agency Site", 
    shortDesc: "SEO-friendly, modern design for high conversion.", 
    fullDesc: "A modern digital agency website designed to capture leads and showcase portfolio work effectively.",
    techStack: ["Html", "CSS", "Js", "Bootstrap"],
    challenge: "Creating a unique visual identity that stands out from typical bootstrap templates.",
    solution: "Used custom grid layouts and scroll-triggered animations to create an immersive storytelling experience.",
    link: "https://connectogrowth.com",
    image: "/projects/connectogrowth.png",
  },
  { 
    id: "expense-manager",
    title: "Expense Manager", 
    tag: "Productivity", 
    shortDesc: "Production-ready, clean UI, analytics, categories.", 
    fullDesc: "A minimalist yet powerful expense tracker built to help users understand their spending habits through visual data. Features include category-wise breakdown, monthly limits, and export to CSV.",
    techStack: ["Flutter", "SQLite", "GetX", "Charts_flutter"],
    challenge: "Creating a local-first architecture that syncs efficiently when online without data conflict.",
    solution: "Used a local SQLite database as the source of truth, with a sync-adapter pattern that pushes changes to the cloud only when connectivity is restored.",
    link: "https://play.google.com/store/apps/details?id=com.shreythakkar.expensemanager",
    image: "/projects/expensemanagermockup.png",
  },
  { 
    id: "statmize",
    title: "Statmize App", 
    tag: "Flutter & IoT", 
    shortDesc: "Real-time Data Display & full app development.", 
    fullDesc: "Statmize is a comprehensive IoT solution designed to bridge the gap between hardware sensors and user-friendly mobile interfaces. It handles complex Bluetooth connection to stream data in real-time.",
    techStack: ["Flutter", "Dart","Firebase"],
    challenge: "Handling high-frequency data packets (20ms interval) from the Hardware without freezing the UI thread on older Android devices.",
    solution: "Implemented a custom Stream buffer in Dart using Isolate (background threads) to process raw hex data before sending it to the UI layer, resulting in 60FPS performance.",
    link: "#",
    image: "/projects/statmizeappmockup.png",
  },
  { 
    id: "multiplayer-game",
    title: "Bubble Reaction Game", 
    tag: "Flutter & Firebase", 
    shortDesc: "A Multi Player Game with Real-time gameplay.", 
    fullDesc: "A real-time multiplayer game that utilizes Firebase Realtime Database for low-latency player synchronization.",
    techStack: ["Flutter", "Firebase Realtime DB", "Cloud Functions",],
    challenge: "Syncing player movement across devices with varying network speeds.",
    solution: "Implemented client-side prediction and server reconciliation to ensure smooth gameplay even on 3G networks.",
    link: "https://indusapp.store/rynxp1mg",
    image: "/projects/bubblereactionmockup.png",
  }
  
];